export const PHASE_START = 'Game start'
export const PHASE = {
    DRAW_PHASE: 'Draw',
    STANDBY_PHASE: 'Standby',
    MAIN_PHASE_1: 'MP1',
    BATTLE_PHASE: 'Battle',
    MAIN_PHASE_2: 'MP2',
    END_PHASE: 'End'
}

export const BATTLE_STEP = {
    START_STEP: "START_STEP",
    DAMAGE_STEP: "DAMAGE_STEP",
    END_STEP: "END_STEP"
}


export const CARD_SELECT_TYPE = {
    CARD_SELECT_TRIBUTE_SUMMON:          'CARD_SELECT_TRIBUTE_SUMMON',
    CARD_SELECT_BATTLE_SELECT:           'CARD_SELECT_BATTLE_SELECT',
    CARD_SELECT_SPECIAL_SUMMON_TARGET:   'CARD_SELECT_SPECIAL_SUMMON_TARGET',
    CARD_SELECT_SPECIAL_SUMMON_MATERIALS:'CARD_SELECT_SPECIAL_SUMMON_MATERIALS',
    // Search / GY selection
    CARD_SELECT_FROM_DECK:               'CARD_SELECT_FROM_DECK',
    CARD_SELECT_FROM_HAND:               'CARD_SELECT_FROM_HAND',
    CARD_SELECT_FROM_GY:                 'CARD_SELECT_FROM_GY',
    // Extra-deck summoning
    CARD_SELECT_RITUAL_MONSTER:          'CARD_SELECT_RITUAL_MONSTER',
    CARD_SELECT_RITUAL_TRIBUTE:          'CARD_SELECT_RITUAL_TRIBUTE',
    CARD_SELECT_SYNCHRO_TARGET:          'CARD_SELECT_SYNCHRO_TARGET',
    CARD_SELECT_SYNCHRO_MATERIALS:       'CARD_SELECT_SYNCHRO_MATERIALS',
    CARD_SELECT_XYZ_TARGET:              'CARD_SELECT_XYZ_TARGET',
    CARD_SELECT_XYZ_MATERIALS:           'CARD_SELECT_XYZ_MATERIALS',
    CARD_SELECT_PENDULUM_SCALE:          'CARD_SELECT_PENDULUM_SCALE',
    CARD_SELECT_PENDULUM_TARGETS:        'CARD_SELECT_PENDULUM_TARGETS',
    CARD_SELECT_LINK_MATERIALS:          'CARD_SELECT_LINK_MATERIALS',
    CARD_SELECT_LINK_TARGET:             'CARD_SELECT_LINK_TARGET',
}

export const MONSTER_ATTACK_TYPE = {
    DIRECT_ATTACK: 'DIRECT_ATTACK',
    OTHERS_ATTACK: 'OTHERS_ATTACK'
}

// to show that the dst is the player (instead of a monster)
export const DST_DIRECT_ATTACK = "DST_DIRECT_ATTACK"